# Generated by Django 5.1.4 on 2025-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready to Board'), ('boarding', 'Boarding'), ('landed', 'Landed')], default='ready', max_length=20),
        ),
    ]
