# Generated by Django 5.1.4 on 2025-01-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
