# Generated by Django 5.1.4 on 2025-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_completed_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Null', 'Not Started'), ('ready', 'Ready to Board'), ('boarding', 'Boarding'), ('landed', 'Landed')], default='null', max_length=20),
        ),
    ]
