# Generated by Django 5.1.4 on 2025-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Null', 'Not Started'), ('Ready', 'Ready to Board'), ('Boarding', 'Boarding'), ('Landed', 'Landed')], default='null', max_length=20),
        ),
    ]
