# Generated by Django 5.1.4 on 2025-02-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_rename_passengers_passenger'),
    ]

    operations = [
    ]
