# Generated by Django 5.1.4 on 2025-02-18 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20250218_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarding_pass',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
